edeliver/edeliver

libexec/core
If path contains underscores, strategies won't be found
=> allow to find strategies in paths with underscore its name

mix.exs
fixes https://github.com/boldpoker/edeliver/issues/22
=> fix wrong placement of `deps` in mix.exs

libexec/erlang
deployment fails if hex isn't installed and mix asks for installing hex which requires manual interaction
```sh
vagrant@edeliver-vagrant ~/b/e/ed ❯❯❯ mix deps.get
Could not find hex, which is needed to build dependency :phoenix
Shall I install hex? [Yn]
```
=> install hex non-interactive

bin/deliver, bin/edeliver
This is the change I suggested in [Issue #57](https://github.com/boldpoker/edeliver/issues/57).
=> Fix 'No such file or directory' caused by incorrect BASE_PATH

doc/auto-versioning.md, doc/configuration.md, lib/mix/tasks/edeliver.ex, lib/mix/tasks/release_version.ex, libexec/erlang, libexec/erlang-init, mix.exs, strategies/erlang-build-release, strategies/erlang-build-upgrade, strategies/erlang-node-execute, strategies/erlang-upgrade, test/release_version_test.exs, test/test_helper.exs
Implement auto-versioning by appending metadata like git commit count, git revision, branch etc. to the release version when building releases and upgrades. 
Also add the ability to auto-increment the version for the current build.
Updating and identifying the version is essential especially when building upgrades.
```sh
mix release.version show
1.0.0
mix edeliver build release --auto-version=commit-count
mix edeliver build upgrade --auto-version=git-revision
mix edeliver build upgrade --auto-version=commit-count+git-revision
mix edeliver build upgrade --auto-version=git-revision+commit-count
```
```sh
mix release.version show
1.0.0
mix edeliver build release --auto-version=git-branch
mix edeliver build release --auto-version=git-revision+git-branch-unless-master
mix edeliver build …
```
=> Add Auto-Versioning

strategies/erlang-node-execute
The option `down` never gets evaluated because of the misspelling in the bash script.
=> Fix syntax on migrate task with down operation

lib/edeliver.ex
When auto detecting Ecto repos, first utilize Ecto 2.0 requirement of `:ecto_repos` in the application env config.
Then fallback to Ecto 1.0 `__repo__` function export detection.
ref GH-70
=> Ecto repos config

lib/edeliver.ex
Sorry, my previous PR #71 had a stupid mistake. My test project wasn't actually testing the new logic like I thought, since I had specified an `ECTO_REPOSITORY` in my `.deliver/config`
=> migrate: fix Application fetch_env pattern match

strategies/erlang-upgrade
If deploy environment is production, the deploy directory
`DELIVER_TO` was not set correctly because it is set to
`BUILD_AT` while building the upgrade. See #49
=> Fix `upgrade` command for production deploy environment

libexec/erlang, strategies/erlang-node-execute
The `restart` command only restarts the current apps without restarting the vm and without booting the deployed release. This does not make sense for edeliver as a deployment tool. Mapping edelivers `restart`  command to the exrm/relx `reboot` command would work only if the node is monitored and restarted by the `heard` command. So edeliver will use the combination of the `stop` and `start` node commands for the edeliver `restart` command.
=> Restart erlang vm with most recent release for edeliver `restart` commands

README.md, lib/edeliver.ex, lib/edeliver/startup_progress.ex, libexec/erlang, libexec/erlang-init, mix.exs, strategies/erlang-node-execute
Wait until all apps are started for the (re)start command and display progress of started applications if the `--verbose` option is used.
=> Synchronous start

libexec/erlang, strategies/erlang-node-execute, strategies/erlang-upgrade
Since exrm version `1.0.5` [removes the output of the currently used script again](https://github.com/bitwalker/exrm/commit/6df2765b27e29dc910be959a49385951d68d83f9) we can't tail the node output any more. To be compatible with previous (and future) exrm versions the number lines of extra output is calculated from the `ping` command and only the additional lines are removed from
the output. In addition a common function is used to generate the node command. See #88.
=> exrm 1.0.5 compatibility

libexec/core
It seems that the agent forwarding was only working in verbose mode.
This allows to use it without the verbose flag.
=> Fix ssh forwarding in non-verbose mode

README.md, lib/distillery/plugins/link_config.ex, mix.exs, strategies/publish-edeliver
to be able to use distillery as build tool. This requires to add `exrm` as dependency to all new projects using edeliver and exrm as build tool. See #132
=> Use exrm as optional dependency

libexec/erlang
This expands the existing workaround to include the additional mix versions that contain the issue. It appears that Elixir 1.3.4 will contain the mix compilation fix. https://github.com/elixir-lang/elixir/issues/5094#issuecomment-252489258
=> Build deps explicitly for mix version `1.3.[0123]`

mix.exs
Fixes several annoying warnings like:
```
warning: variable "elixirc_paths" does not exist and is being expanded to "elixirc_paths()", please use parentheses to remove the ambiguity or change the variable name
```
every time our project is run/tested with Elixir 1.4.
=> Fix warnings with Elixir 1.4

README.md
The sentence "and your build tool" was duplicated. Also fixed a few tabs vs. spaces inconsistencies in the sample `mix.exs` config.
=> Fix duplicated sentence in the README file.

libexec/core
Project path can contain spaces. 
This change:
- updates regex to include space character,
- updates bash for-in loop internal field separator ([IFS](http://www.tldp.org/LDP/abs/html/internalvariables.html#IFSREF)) to newline (instead of whitespace, i.e. space, tab, and newline), reverts to default value after iterating.
=> Added support for spaces in project path. Close #179.

libexec/core
Reverts edeliver/edeliver#180
It broke using multiple hosts. See #226.
=> Revert "Added support for spaces in project path. Close #179."

docs/relup-patching.md, lib/distillery/plugins/link_config.ex, lib/distillery/plugins/modify_relup.ex, mix.exs
- There was no mention in the documentation that you had to add configuration to distillery to tell it to use the `Releases.Plugin.ModifyRelup` plugin. This may need to be made even more obvious in the README or something?
- The plugin was using the wrong `output_dir` (so it was never able to find the `relup_file` and was silently skipping the modifications)
- Docs weren't being generated/published for the distillery plugins
- Fixed some typos in docs (references to exrm instead of distillery in the plugins, and the relup patching docs sample trying to pass an atom to String.to_atom)
=> Updates to distillery integration

lib/distillery/plugins/link_config.ex
Even if distillery's `output_dir` and `RELEASE_DIR` is configured, LinkConfig plugin always reference default `output_dir` path(`_build/prod/rel/$APP`).
[According to bitwalker's comment](https://github.com/bitwalker/distillery/issues/367#issuecomment-348302981), should use `release.profile.output_dir` for the precise configuration.
cf. https://github.com/edeliver/edeliver/issues/219
=> Should use `profile.output_dir` instead `output_dir` in LinkConfig plugin

README.md, libexec/common, libexec/erlang, libexec/erlang-init, strategies/erlang-deploy-upgrade, strategies/erlang-update, strategies/erlang-upgrade
Make all shell scripts on deploy hosts POSIX compatible. This allows to use there any shell as default shell (instead of requiring bash or zsh). Closes #143.
=> POSIX compatibility

strategies/erlang-build-upgrade
Solution: Update output folder for non-rebar upgrades
This will break exrm compatibility, which is not that bad since exrm shouldn't be used anymore.
Details: https://github.com/bitwalker/distillery/blob/master/CHANGELOG.md#changed-6
closes #182
=> Problem: Upgrade with Distillery failure due to changed output folder

.gitignore, mix.exs, mix.lock, test/release_version_test.exs, test/test_helper.exs
`:os.cmd()` uses dash by default on ubuntu. Dash does not support `<<<`. So just before giving up, I found out that the bash command supports a -c option, so `<<<` can be avoided completely.
Bonus: This has the advantage that the exit status is properly propagated.
=> Make tests run everywhere

lib/edeliver/relup/instructions/check_ranch_acceptors.ex
Seems that it was removed in 1.3 in favor of Phoenix.Endpoint.Handler
=> bug: Ranch process is not being detected in Phoenix 1.3

lib/distillery/plugins/link_config.ex, lib/distillery/plugins/modify_relup.ex, lib/edeliver.ex
fix below warnings.
- `Kernel.to_char_list/1 is deprecated`
- `Mix.Releases.Plugin` behaviour needs callback functions
- `Stream.filter_map/3 is deprecated`
-  delete not using val
- `GenServer` behaviour needs init/1 func
=> Fix some warnings

docs/auto-versioning.md, lib/mix/tasks/release_version.ex, test/release_version_test.exs
Hi autoversion-ing is great,
currently I'm using this format `AUTO_VERSION="build-date+revision"`
but I can deploy multiple times a day and the git `revision` is just a random string and cannot be properly sorted, while `commit-count` is great, it doesn't tell you anything contextual
so my PR will add new autoversion format `time`, to append local time to autoversion, so I can use it like this `AUTO_VERSION="build-date+time+revision"`
=> New autoversion -time

lib/distillery/plugins/link_config.ex, lib/distillery/plugins/modify_relup.ex
First in distillery's Mix.Releases.Plugin, watching 2-arity function, otherwise 1-arity: https://github.com/bitwalker/distillery/blob/master/lib/mix/lib/releases/plugins/plugin.ex#L211
Plugins was broken by this commit: https://github.com/edeliver/edeliver/commit/3fbcda05756c7475686410cc4c9964edbaf72d2f#diff-54433280d02e1346367d6df697291dd7. Empty 2-arity functions added, but logic remains in 1-arity functions.
Please, check my fixes/
=> Fix plugins

libexec/erlang
This will make git clean cd to the correct path BUILD_AT instead of DELIVER_TO. DELIVER_TO is the path of the deploy host while BUILD_AT is the build server that needs to be cleaned.
Also fix git clean with multiple long paths "_build/edge/rel rel/app priv/static/generated"
=> Fix git clean remote

libexec/erlang
this gets rid of the annoying
```
bash: line 3501: warning: here-document at line 4 delimited by end-of-file (wanted `EOF')
```
by uploading things to s3 and deploying
line  its caused by syntax annoyance handling of bash, see https://www.krenger.ch/blog/bash-here-document-at-line-n-delimited-by-end-of-file-wanted-eof/
also if you could please cut a release after merging this in. I would really appreciate it. Because then I could update my project's mix file and get these errors out of my life.
=> annoying eof warning be gone!

libexec/defaults, libexec/erlang-init, mix.exs
Currently with `{:edeliver, "~> 1.6"}` the `build-time` option for the `--auto-version` flag does not work. 
For example the command `mix edeliver build release --auto-version=build-time` returns the error: `Illegal value for --auto-version= option: 'build-time'.`
The problem is that the shell scripts that pass the options along were not updated with the relevant Elixir code. The PR updates those scripts to accept `bulild-time`, as well as updating some script info, and bumping the version code.
Let me know if bumping the version shouldn't be part of this PR, and I can revert.
=> Allow time to be passed for auto-version and correct version info.

lib/distillery/plugins/link_config.ex, lib/distillery/plugins/modify_relup.ex, lib/edeliver/relup/release_config.ex, mix.exs, mix.lock
Per [this changelog](https://hexdocs.pm/distillery/changelog.html#breaking-changes), Distillery renamed a few of their modules to be compatible with [Elixir 1.9's releases](https://elixir-lang.org/blog/2019/06/24/elixir-v1-9-0-released/). This, in turn, broke edeliver for users on 1.9 who still wish to use the Distillery/edeliver flow (mostly, for those who want relups and/or 
Note that this bumps edeliver's minimum version requirements to Elixir 1.9, so this should probably be a major release if it (or something like it) is merged in. Happy to do additional work if asked 😄
=> Compatibility with Distillery 2.10.0 and Elixir 1.9

libexec/erlang
See https://hexdocs.pm/distillery/changelog.html#210-unreleased (2.1.0 changelog)
=> `release` task was renamed to `distillery.release`

libexec/erlang
problem:
```
mix edeliver build release --branch=develop --verbose
......
Dependencies have diverged:
* hackney (https://github.com/benoitc/hackney.git)
different specs were given for the hackney app:
> In apps/foo/mix.exs:
{:hackney, [env: :prod, git: "https://github.com/benoitc/hackney.git", override: true]}
> In deps/bar/apps/baz/mix.exs:
{:hackney, "~> 1.9", [only: :test, env: :prod, repo: "hexpm", hex: "hackney"]}
Ensure they match or specify one of the above in your deps and set "override: true" 
** (Mix) Can't continue due to errors on dependencies
```
I needed `mix deps.get --only prod` with somewhat complex dependencies.
I think we need to pass options to `mix deps.get`.
NOTE: this is a quick & dirty solution for my case. i just needed deps with [only: test] to be excluded when …
=> added '--only prod' option at mix get.deps.

libexec/erlang
I have a use case where I need to clean up some files before extracting the deploy archive, since the extract doesn't remove older versions. Being execute just before the extracting process was the ideal scenario, so I've added `pre_extract_release_archive` hook.
=> Add pre_extract_release_archive hook

README.md, libexec/app_config, libexec/core, libexec/erlang
See: [rebar3](https://github.com/erlang/rebar3) which is the successor of rebar2.x and how to [migrate from rebar 2 to rebar 3](https://rebar3.org/docs/tutorials/from_rebar2_to_rebar3/).
=> Build releases using rebar3

README.md, docker/release-base.dockerfile, libexec/core, libexec/erlang, libexec/erlang-init
if an image in a (private) docker registry is configured as `RELEASE_STORE`. The image is based on the `DOCKER_RELEASE_BASE_IMAGE` (which defaults to `edeliver/release-base`) and will be pushed with 3 tags: *release version* + *latest*, *release version* + *git sha* and *release version* + *branch*. The release can then be started like this:
```sh
docker start -ti edeliver/echo-server:1.0-latest -p 8080:8080 echo-server/bin/echo-server console
```
Closes #121
=> Build release as docker image

libexec/erlang
and print warnings otherwise, that the `--push` flag is ignored. 
See: https://elixirforum.com/t/config-edeliver-build-in-docker-and-deploy-as-docker/47038/3
=> Enable --push only for docker registry release stores

libexec/erlang
instead of using docker tag as version. The tag contains an additional `-latest` or `-<git-sha>` suffix.
This won't work for release versions containg `-` characters. To fix this, the actual release version needs to added as
metadata to the docker image for instance.
=> Use release version when linking vm args into container

libexec/erlang
I noticed when using `mix release` to build a release (in Docker) there is no `{$APP}.tar.gz` file.
This PR adds the missing functionality.
=> Support tarred file using `mix release`

.github/workflows/build-in-docker.yml, test/build-in-docker/build-distillery.sh, test/build-in-docker/build-mix.sh
Add GitHub action to build a mix project on CI either with the builtin release tool or with distillery.
=> Build mix project in docker on CI

mix.exs
Script was failing to copy over `/docker/start_container` as it doesn't exist in the package from hex.
```
-----> Uploading archive of release 0.1.091d08c2-lorenzoedeliver-latest from docker release store
-----> Extracting container start script into /home/docker/apps/project/bin
cat: /Users/lorenzo/projects/project/deps/edeliver/docker/start_container: No such file or directory
Copied edeliver default script
Using edeliver default script.\nPlease consider to add your own version at /project/bin/start_container.\n
DEPLOYED RELEASE TO PRODUCTION!
```
=> fix: add docker folder to mix package

libexec/erlang
since the for loop is piped, variables assigned in it will not be set outside the loop and it cannot be detected later whether detailed tag info were found or not.
=> Fix detecting detailed tag info

CHANGELOG.md, libexec/erlang
If the release base image set as `DOCKER_RELEASE_BASE_IMAGE`, contains a workdir set to the application dir - which makes sense - e.g. `WORKDIR /my-app` and the built release is copied with `docker cp` to `release-container:/my-app`, it will end up unexpectedly in `/my-app/my-app` - which is not the goal. According [to the docs](https://docs.docker.com/engine/reference/builder/#workdir):
> The WORKDIR instruction sets the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions
and the unexpected result seen if the `WorkingDir` is set in the container config, we can avoid copying to the workdir as subdir if we set another temporary workdir while copying. If this is a different dir (e.g. `/tmp`), the release won't end up in `/tmp/my-app` but in the expected `/my-app` root …
=> Handle workdir set in DOCKER_RELEASE_BASE_IMAGE
